POST http://localhost:3005/api/blogs/ HTTP/1.1
Content-Type: application/json

{
 "user": "649a5176338da048a8a19b5e",
 "title": "Ziran", 
 "author": "The tester", 
 "url": "across the universe", 
 "likes": 16
}